# Site settings

name: Joseph Fusco
role: Front End Developer. WordPress Core Contributor.
intro-line-1: Hello, I'm Joe,
intro-line-2: and I build things for the web.
description: Rochester, NY Web Developer. WordPress Core Contributor.
url: "https://josephfus.co"
email: hello@josephfus.co

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: josephfus.co
ga_tracking_id: UA-57969250-1

# Accounts

accounts:

  - name: CodePen
    url: https://codepen.io/fusco

  - name: GitHub
    url:  https://github.com/josephfusco

  - name: WordPress
    url: https://profiles.wordpress.org/joefusco

# Portfolio Page (Index)

portfolio:

  - title: Snowy Escape
    subtitle: Website
    url: http://snowyescape.com/
    imageFileName: snowyescape.jpg

  - title: Angled Edges
    subtitle: Sass Utility
    url: https://angled-edges.josephfus.co/
    imageFileName: angled-edges.svg

  - title: APFT Calculator
    subtitle: Web Application
    url: https://apft.metttc.com
    imageFileName: apft.svg

  - title: WP Git Branch
    subtitle: WordPress Plugin
    url: https://github.com/josephfusco/wp-git-branch
    imageFileName: git-branch.svg

  - title: Underscores Generator
    subtitle: WordPress Plugin
    url: https://github.com/josephfusco/_s-generator
    imageFileName: underscores-generator.svg

  - title: Advanced Custom Fields Viewer
    subtitle: WordPress Plugin
    url: https://wordpress.org/plugins/advanced-custom-fields-viewer/
    imageFileName: acfv.jpg

  - title: Select64
    subtitle: Web Application
    url: http://select64.josephfus.co/
    imageFileName: select64.jpg

  - title: WP Self Destruct
    subtitle: WordPress Plugin
    url: https://github.com/josephfusco/wp-self-destruct/
    imageFileName: wp-self-destruct.svg

  - title: CSS Tabs
    subtitle: CodePen
    url: https://codepen.io/fusco/pen/Wvzjrm
    imageFileName: css-tabs.gif

  - title: Sass Candle Flicker
    subtitle: CodePen
    url: http://codepen.io/fusco/pen/NPxzPV
    imageFileName: sass-candle-flicker.gif

  - title: IG Follow Count
    subtitle: Instagram Analytics Tool
    url: https://github.com/josephfusco/ig-follow-count/
    imageFileName: ig-follow-count.jpg

  - title: CSS iMessage Typing Indicator
    subtitle: CodePen
    url: https://codepen.io/fusco/pen/XbpaYv
    imageFileName: css-imessage.gif

  - title: Disable Responsive Images
    subtitle: WordPress Plugin
    url: https://wordpress.org/plugins/disable-responsive-images/
    imageFileName: disable-responsive-images.svg

  - title: Condensed Bootstrap Grid
    subtitle: Sass Grid System
    url: https://github.com/josephfusco/condensed-bootstrap-grid/
    imageFileName: condensed-bootstrap-grid.svg

# Markdown settings

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - CNAME
  - node_modules
  - assets/sass/

# Plugin settings

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
